import WebSocket from 'ws';
import { v4 as uuidv4 } from 'uuid';
import {
  AbilityLimitGroupState,
  AbilityLimitStateMessage,
  ActionMessage,
  ActionRejectReason,
  ActionResultMessage,
  GameFinishedMessage,
  SessionBootPhase,
  SessionListEntry,
  SpectatorAction,
  SpectatorEntry,
} from '../protocol/messages';
import { buildPublicObjectUrl, ObjectStorage, StoredAsset } from '../storage/ObjectStorage';

interface AbilityRateLimitDefinition {
  action: string;
  targetingMode: string;
  cooldownMs: number;
  groupId: string;
  groupLabel: string;
  category: string;
  capacity: number;
  refillMs: number;
  valid: boolean;
}

interface AbilityLimitBucket {
  groupId: string;
  label: string;
  category: string;
  capacity: number;
  refillMs: number;
  tokens: number;
  lastRefillAt: number;
}

interface CachedActionResult {
  result: ActionResultMessage;
  expiresAt: number;
}

interface SpectatorConnection extends SpectatorEntry {
  spectatorToken?: string;
  joinedOrder: number;
}

interface SpectatorParticipant {
  spectatorId: string;
  spectatorName: string;
  joinedOrder: number;
}

export class Session {
  public readonly sessionId: string;
  public readonly playerName: string;
  public readonly level: string;
  public readonly createdAt: Date;
  public playerConnection: WebSocket;

  private spectators: Map<WebSocket, SpectatorConnection> = new Map();
  private spectatorParticipants: Map<string, SpectatorParticipant> = new Map();
  private mapImage: object | null = null;
  private mapTiles: object | null = null;
  private mapTileAssets: Map<string, { mimeType: string; data: Buffer }> = new Map();
  private mapTileAssetBytes = 0;
  private mapTileUploadPromises: Map<string, Promise<void>> = new Map();
  private mapTileDownloadUrlCache: Map<string, { url: string; expiresAt: number }> = new Map();
  private mapObjects: object | null = null;
  private routeLayout: object | null = null;
  private abilityManifest: object | null = null;
  private weaponManifest: object | null = null;
  private drops: Map<string, object> = new Map(); // dropId → drop_spawn message
  private spectatorDamage: Map<string, number> = new Map(); // cumulative damage per spectator name
  private spectatorNameAliases: Map<string, string> = new Map();
  private abilityLimitsReady = false;
  private abilityDefinitions: Map<string, AbilityRateLimitDefinition> = new Map();
  private abilityLimitBuckets: Map<string, AbilityLimitBucket> = new Map();
  private personalCooldowns: Map<string, Map<string, number>> = new Map();
  private cachedActionResults: Map<string, Map<string, CachedActionResult>> = new Map();
  private bootPhase: SessionBootPhase = 'booting';
  private bootMessage = 'Map being generated by host.';
  private routeReady = false;
  private finishedResult: GameFinishedMessage | null = null;
  private nextSpectatorJoinOrder = 0;
  private lastPlayerDeaths = 0;
  private hasPlayerDeathSnapshot = false;

  private pendingGameState: object | null = null;
  private gameStateFlushTimer: NodeJS.Timeout | null = null;
  private lastGameStateSentAt = 0;

  private static readonly GAME_STATE_MIN_INTERVAL_MS = 33;
  private static readonly MAP_TILE_CACHE_LIMIT_BYTES =
    Math.max(8, parseInt(process.env.MAP_TILE_CACHE_LIMIT_MB || '128', 10)) * 1024 * 1024;

  constructor(playerName: string, level: string, playerConnection: WebSocket, private readonly objectStorage: ObjectStorage) {
    this.sessionId = uuidv4().slice(0, 8);
    this.playerName = playerName;
    this.level = level;
    this.playerConnection = playerConnection;
    this.createdAt = new Date();
  }

  get spectatorCount(): number {
    return this.spectators.size;
  }

  get isFinished(): boolean {
    return this.finishedResult !== null;
  }

  /** Adds a spectator or moves an existing token to a replacement socket. */
  addSpectator(
    ws: WebSocket,
    spectatorName: string,
    spectatorToken?: string,
  ): { spectatorId: string; replacedWs?: WebSocket } | null {
    if (spectatorToken) {
      for (const [existingWs, entry] of this.spectators) {
        if (entry.spectatorToken !== spectatorToken) continue;

        this.spectators.delete(existingWs);
        this.spectators.set(ws, entry);
        this.broadcastSpectatorCount();
        this.broadcastSpectatorList();
        return { spectatorId: entry.spectatorId, replacedWs: existingWs };
      }
    }

    if (this.finishedResult) return null;

    const nameLower = spectatorName.toLowerCase();
    if (this.spectatorNameAliases.has(nameLower)) return null;
    for (const [, entry] of this.spectators) {
      if (entry.spectatorName.toLowerCase() === nameLower) return null;
    }
    const spectatorId = uuidv4().slice(0, 8);
    const connection = {
      spectatorId,
      spectatorName,
      spectatorToken,
      joinedOrder: this.nextSpectatorJoinOrder++,
    };
    this.spectators.set(ws, connection);
    this.spectatorParticipants.set(spectatorId, {
      spectatorId,
      spectatorName,
      joinedOrder: connection.joinedOrder,
    });
    this.broadcastSpectatorCount();
    this.broadcastSpectatorList();

    return { spectatorId };
  }

  replayCachedState(ws: WebSocket): void {
    if (this.routeLayout && ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(this.routeLayout));
    }
    // Send cached map data to new spectator
    if (this.mapImage && ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(this.mapImage));
    }
    if (this.mapTiles && ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(this.mapTiles));
    }
    if (this.mapObjects && ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(this.mapObjects));
    }
    if (this.abilityManifest && ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(this.abilityManifest));
    }
    if (this.weaponManifest && ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(this.weaponManifest));
    }
    // Send currently active drops so the new spectator sees existing ground items
    if (ws.readyState === WebSocket.OPEN) {
      for (const drop of this.drops.values()) {
        ws.send(JSON.stringify(drop));
      }
    }
    // Send damage snapshot so late-joiners see the correct leaderboard immediately
    if (ws.readyState === WebSocket.OPEN && this.spectatorDamage.size > 0) {
      const snapshot: Record<string, number> = {};
      for (const [name, dmg] of this.spectatorDamage) snapshot[name] = dmg;
      ws.send(JSON.stringify({ type: 'spectator_damage_snapshot', damage: snapshot }));
    }

    if (ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(this.createSessionStatusMessage()));
      this.sendAbilityLimitState(ws);
      if (this.finishedResult) ws.send(JSON.stringify(this.finishedResult));
    }
  }

  removeSpectator(ws: WebSocket): void {
    this.spectators.delete(ws);
    this.broadcastSpectatorCount();
    this.broadcastSpectatorList();
  }

  hasSpectator(ws: WebSocket): boolean {
    return this.spectators.has(ws);
  }

  getSpectatorName(ws: WebSocket): string | undefined {
    return this.spectators.get(ws)?.spectatorName;
  }

  getSpectatorToken(ws: WebSocket): string | undefined {
    return this.spectators.get(ws)?.spectatorToken;
  }

  renameSpectator(ws: WebSocket, spectatorName: string): string | null {
    const entry = this.spectators.get(ws);
    if (!entry) return 'You are not in this session.';
    if (this.finishedResult) return 'This arena has already finished.';

    const nextName = spectatorName.trim();
    const oldName = entry.spectatorName;
    const oldKey = oldName.toLowerCase();
    const nextKey = nextName.toLowerCase();
    const aliasedOwner = this.spectatorNameAliases.get(nextKey);
    if (aliasedOwner && aliasedOwner.toLowerCase() !== oldKey) {
      return 'Name already used in this session.';
    }
    for (const [otherWs, other] of this.spectators) {
      if (otherWs !== ws && other.spectatorName.toLowerCase() === nextKey) {
        return 'Name already taken in this session.';
      }
    }
    if (oldName === nextName) return null;

    entry.spectatorName = nextName;
    const participant = this.spectatorParticipants.get(entry.spectatorId);
    if (participant) participant.spectatorName = nextName;
    this.spectatorNameAliases.set(oldKey, nextName);
    for (const [alias, target] of this.spectatorNameAliases) {
      if (target.toLowerCase() === oldKey) {
        this.spectatorNameAliases.set(alias, nextName);
      }
    }

    const oldDamage = this.findDamageEntry(oldKey);
    if (oldDamage) {
      this.spectatorDamage.delete(oldDamage[0]);
      const current = this.findDamageEntry(nextKey);
      const total = oldDamage[1] + (current?.[1] ?? 0);
      if (current) this.spectatorDamage.delete(current[0]);
      this.spectatorDamage.set(nextName, total);
    }
    this.moveSpectatorMap(this.personalCooldowns, oldKey, nextKey);
    this.moveSpectatorMap(this.cachedActionResults, oldKey, nextKey);

    this.broadcastSpectatorList();
    this.broadcastDamageSnapshot();
    return null;
  }

  sendToPlayer(data: object): void {
    if (this.playerConnection.readyState === WebSocket.OPEN) {
      this.playerConnection.send(JSON.stringify(data));
    }
  }

  sendToSpectators(data: object): void {
    const message = JSON.stringify(data);
    for (const [ws] of this.spectators) {
      if (ws.readyState === WebSocket.OPEN && ws.bufferedAmount < 512_000) {
        ws.send(message);
      }
    }
  }

  private forwardActionToPlayer(spectatorWs: WebSocket, action: SpectatorAction, worldX?: number, worldZ?: number): void {
    const spectatorName = this.spectators.get(spectatorWs)?.spectatorName;
    const targeted = worldX !== undefined && worldZ !== undefined;
    const message = {
      type: 'event',
      action,
      worldX: worldX ?? 0,
      worldZ: worldZ ?? 0,
      targeted,
      spectatorName,
    };

    this.sendToPlayer(message);
    this.sendToSpectators(message);
  }

  hasCachedActionResult(spectatorWs: WebSocket, requestId: string): boolean {
    const spectatorKey = this.getSpectatorKey(spectatorWs);
    if (!spectatorKey) return false;
    this.pruneCachedActionResults(spectatorKey);
    return this.cachedActionResults.get(spectatorKey)?.has(requestId) ?? false;
  }

  rejectAction(
    spectatorWs: WebSocket,
    requestId: string,
    action: SpectatorAction,
    reason: ActionRejectReason,
    retryAfterMs?: number,
  ): false {
    return this.sendActionResult(spectatorWs, {
      type: 'action_result',
      requestId,
      action,
      accepted: false,
      reason,
      ...(retryAfterMs && retryAfterMs > 0 ? { retryAfterMs: Math.ceil(retryAfterMs) } : {}),
    });
  }

  tryForwardAction(spectatorWs: WebSocket, request: ActionMessage): boolean {
    const spectatorKey = this.getSpectatorKey(spectatorWs);
    if (!spectatorKey) return this.rejectAction(spectatorWs, request.requestId, request.action, 'unknown_action');

    if (this.finishedResult) {
      return this.rejectAction(spectatorWs, request.requestId, request.action, 'game_finished');
    }

    this.pruneCachedActionResults(spectatorKey);
    const cached = this.cachedActionResults.get(spectatorKey)?.get(request.requestId);
    if (cached) {
      this.sendDirect(spectatorWs, cached.result);
      return cached.result.accepted;
    }

    if (!this.abilityLimitsReady) {
      return this.rejectAction(spectatorWs, request.requestId, request.action, 'manifest_not_ready');
    }

    const definition = this.abilityDefinitions.get(request.action);
    if (!definition) {
      return this.rejectAction(spectatorWs, request.requestId, request.action, 'unknown_action');
    }
    if (!definition.valid) {
      return this.rejectAction(spectatorWs, request.requestId, request.action, 'missing_profile');
    }

    const targeted = request.worldX !== undefined && request.worldZ !== undefined;
    const requiresTarget = definition.targetingMode === 'point' || definition.targetingMode === 'area';
    if (requiresTarget !== targeted) {
      return this.rejectAction(spectatorWs, request.requestId, request.action, 'invalid_target');
    }

    const now = Date.now();
    const personal = this.personalCooldowns.get(spectatorKey)?.get(request.action) ?? 0;
    if (personal > now) {
      return this.rejectAction(spectatorWs, request.requestId, request.action, 'personal_cooldown', personal - now);
    }

    const bucket = this.abilityLimitBuckets.get(definition.groupId);
    if (!bucket) {
      return this.rejectAction(spectatorWs, request.requestId, request.action, 'missing_profile');
    }
    this.refillBucket(bucket, now);
    if (bucket.tokens < 1) {
      return this.rejectAction(spectatorWs, request.requestId, request.action, 'group_limited', this.getBucketRetryAfterMs(bucket, now));
    }

    bucket.tokens -= 1;
    const cooldownEnd = now + definition.cooldownMs;
    let spectatorCooldowns = this.personalCooldowns.get(spectatorKey);
    if (!spectatorCooldowns) {
      spectatorCooldowns = new Map();
      this.personalCooldowns.set(spectatorKey, spectatorCooldowns);
    }
    spectatorCooldowns.set(request.action, cooldownEnd);

    this.sendActionResult(spectatorWs, {
      type: 'action_result',
      requestId: request.requestId,
      action: request.action,
      accepted: true,
      personalCooldownMs: definition.cooldownMs,
    });
    this.forwardActionToPlayer(spectatorWs, request.action, request.worldX, request.worldZ);
    this.broadcastAbilityLimitState();
    return true;
  }

  forwardGameState(data: object): void {
    if (this.finishedResult) return;

    const playerDeaths = Number(
      (data as { playerDeaths?: unknown }).playerDeaths,
    );
    if (Number.isFinite(playerDeaths)) {
      this.lastPlayerDeaths = Math.max(0, Math.floor(playerDeaths));
      this.hasPlayerDeathSnapshot = true;
    }

    const now = Date.now();
    const elapsed = now - this.lastGameStateSentAt;

    if (elapsed >= Session.GAME_STATE_MIN_INTERVAL_MS && !this.gameStateFlushTimer) {
      this.lastGameStateSentAt = now;
      this.sendToSpectators(data);
      return;
    }

    this.pendingGameState = data;
    if (this.gameStateFlushTimer) return;

    const delay = Math.max(1, Session.GAME_STATE_MIN_INTERVAL_MS - elapsed);
    this.gameStateFlushTimer = setTimeout(() => {
      this.gameStateFlushTimer = null;
      const pending = this.pendingGameState;
      this.pendingGameState = null;
      if (!pending) return;

      this.lastGameStateSentAt = Date.now();
      this.sendToSpectators(pending);
    }, delay);
  }

  setMapImage(data: object): void {
    this.mapImage = data;
    this.sendToSpectators(data);
  }

  async setMapTiles(data: object): Promise<void> {
    await this.waitForMapTileUploads(120_000);
    this.mapTiles = data;
    this.sendToSpectators(data);
  }

  async setMapTileAsset(path: string, mimeType: string, base64Data: string): Promise<boolean> {
    const cleanPath = path.replace(/^\/+/, '');
    const data = Buffer.from(base64Data, 'base64');
    const storageKey = this.getMapTileStorageKey(cleanPath);
    const existing = this.mapTileAssets.get(cleanPath);
    const nextBytes = this.mapTileAssetBytes - (existing?.data.length ?? 0) + data.length;
    if (!this.objectStorage.enabled && nextBytes > Session.MAP_TILE_CACHE_LIMIT_BYTES) {
      console.warn(
        `[Session] Rejecting map tile "${cleanPath}" for "${this.sessionId}"; cache limit ` +
        `${Math.round(Session.MAP_TILE_CACHE_LIMIT_BYTES / 1024 / 1024)}MB would be exceeded.`
      );
      return false;
    }

    const normalizedMimeType = mimeType || 'image/jpeg';
    if (!this.objectStorage.enabled) {
      this.mapTileAssets.set(cleanPath, {
        mimeType: normalizedMimeType,
        data,
      });
      this.mapTileAssetBytes = nextBytes;
      return true;
    }

    const upload = this.objectStorage.put(storageKey, normalizedMimeType, data)
      .catch((error) => {
        console.warn(`[Session] Failed to upload map tile "${cleanPath}" for "${this.sessionId}": ${error?.message ?? error}`);
        throw error;
      })
      .finally(() => {
        this.mapTileUploadPromises.delete(cleanPath);
      });
    this.mapTileUploadPromises.set(cleanPath, upload);
    await upload;
    return true;
  }

  async getMapTileAsset(path: string): Promise<StoredAsset | null> {
    const cleanPath = path.replace(/^\/+/, '');
    const pendingUpload = this.mapTileUploadPromises.get(cleanPath);
    if (pendingUpload) {
      try {
        await pendingUpload;
      } catch {
        return null;
      }
    }

    if (!this.objectStorage.enabled) {
      return this.mapTileAssets.get(cleanPath) ?? null;
    }

    return this.objectStorage.get(this.getMapTileStorageKey(cleanPath));
  }

  async getMapTileDownloadUrl(path: string): Promise<string | null> {
    const cleanPath = path.replace(/^\/+/, '');
    const pendingUpload = this.mapTileUploadPromises.get(cleanPath);
    if (pendingUpload) {
      try {
        await pendingUpload;
      } catch {
        return null;
      }
    }

    const cached = this.mapTileDownloadUrlCache.get(cleanPath);
    const now = Date.now();
    if (cached && cached.expiresAt > now + 15_000) {
      return cached.url;
    }

    const url = await this.objectStorage.getDownloadUrl(this.getMapTileStorageKey(cleanPath));
    if (url) {
      const ttlSeconds = Math.max(60, parseInt(process.env.MINIO_PRESIGNED_GET_EXPIRY_SECONDS || '300', 10));
      this.mapTileDownloadUrlCache.set(cleanPath, {
        url,
        expiresAt: now + ttlSeconds * 1000,
      });
    }

    return url;
  }

  async clearCachedAssets(): Promise<void> {
    this.mapImage = null;
    this.mapTiles = null;
    this.mapObjects = null;
    this.routeLayout = null;
    this.abilityManifest = null;
    this.weaponManifest = null;
    this.mapTileAssets.clear();
    this.mapTileAssetBytes = 0;
    this.mapTileUploadPromises.clear();
    this.mapTileDownloadUrlCache.clear();
    this.drops.clear();
    this.spectatorDamage.clear();
    this.spectatorNameAliases.clear();
    this.abilityLimitsReady = false;
    this.abilityDefinitions.clear();
    this.abilityLimitBuckets.clear();
    this.personalCooldowns.clear();
    this.cachedActionResults.clear();
    this.pendingGameState = null;
    if (this.gameStateFlushTimer) {
      clearTimeout(this.gameStateFlushTimer);
      this.gameStateFlushTimer = null;
    }

    await this.objectStorage.deletePrefix(this.getSessionStoragePrefix());
  }

  getSessionStoragePrefix(): string {
    return `sessions/${this.sessionId}/`;
  }

  private getMapTileStorageKey(path: string): string {
    return `${this.getSessionStoragePrefix()}map-tiles/${path.replace(/^\/+/, '')}`;
  }

  private async waitForMapTileUploads(timeoutMs: number): Promise<void> {
    const uploads = Array.from(this.mapTileUploadPromises.values());
    if (uploads.length === 0) return;
    const timeout = new Promise<'timeout'>((resolve) => {
      setTimeout(() => resolve('timeout'), timeoutMs);
    });
    const result = await Promise.race([Promise.allSettled(uploads), timeout]);
    if (result === 'timeout') {
      console.warn(`[Session] Timed out waiting for ${uploads.length} map tile upload(s) in "${this.sessionId}". Publishing manifest anyway; missing tiles can retry/404.`);
    }
  }

  getDebugInfo(): object {
    return {
      sessionId: this.sessionId,
      playerName: this.playerName,
      level: this.level,
      createdAt: this.createdAt.toISOString(),
      spectatorCount: this.spectatorCount,
      bootPhase: this.bootPhase,
      bootMessage: this.bootMessage,
      mapTileCount: this.mapTileAssets.size,
      mapTileBytes: this.mapTileAssetBytes,
      mapTiles: this.mapTiles,
      hasMapImage: Boolean(this.mapImage),
    };
  }

  setMapObjects(data: object): void {
    this.mapObjects = data;
    this.sendToSpectators(data);
  }

  setAbilityManifest(data: object): void {
    this.abilityManifest = data;
    this.configureAbilityLimits(data);
    this.sendToSpectators(data);
    this.broadcastAbilityLimitState();
  }

  setWeaponManifest(data: object): void {
    this.weaponManifest = data;
    this.sendToSpectators(data);
  }

  setRouteLayout(data: object): void {
    this.routeLayout = data;
    this.routeReady = true;
    this.bootPhase = 'ready';
    this.bootMessage = 'Arena ready.';
    this.sendToSpectators(data);
    this.broadcastSessionStatus();
  }

  setSessionStatus(phase: SessionBootPhase, message: string | undefined, routeReady: boolean): void {
    this.bootPhase = phase;
    this.bootMessage = message?.trim() || (phase === 'ready' ? 'Arena ready.' : 'Map being generated by host.');
    this.routeReady = routeReady;
    this.broadcastSessionStatus();
  }

  getBootState(): { bootPhase: SessionBootPhase; bootMessage: string; routeReady: boolean } {
    return {
      bootPhase: this.bootPhase,
      bootMessage: this.bootMessage,
      routeReady: this.routeReady,
    };
  }

  recordDamage(spectatorName: string, damage: number): void {
    if (this.finishedResult) return;

    const resolvedName =
      this.spectatorNameAliases.get(spectatorName.trim().toLowerCase()) ??
      spectatorName;
    const existing = this.findDamageEntry(resolvedName.toLowerCase());
    const prev = existing?.[1] ?? 0;
    const total = prev + damage;
    if (existing && existing[0] !== resolvedName) {
      this.spectatorDamage.delete(existing[0]);
    }
    this.spectatorDamage.set(resolvedName, total);
    this.sendToSpectators({
      type: 'spectator_damage',
      spectatorName: resolvedName,
      totalDamage: total,
    });
  }

  addDrop(data: object & { id: string }): void {
    if (this.finishedResult) return;
    this.drops.set(data.id, data);
    this.sendToSpectators(data);
  }

  removeDrop(id: string): void {
    if (this.finishedResult) return;
    this.drops.delete(id);
    this.sendToSpectators({ type: 'drop_destroy', id });
  }

  private configureAbilityLimits(data: object): void {
    this.abilityDefinitions.clear();
    this.abilityLimitBuckets.clear();
    const abilities = Array.isArray((data as { abilities?: unknown[] }).abilities)
      ? (data as { abilities: unknown[] }).abilities
      : [];
    const inconsistentGroups = new Set<string>();

    for (const raw of abilities) {
      if (!raw || typeof raw !== 'object') continue;
      const entry = raw as Record<string, unknown>;
      const action = String(entry.id ?? '').trim();
      if (!action) continue;
      const groupId = String(entry.rateLimitGroupId ?? '').trim();
      const groupLabel = String(entry.rateLimitGroupLabel ?? groupId).trim();
      const category = String(entry.rateLimitCategory ?? '').trim();
      const capacity = Math.floor(Number(entry.rateLimitCapacity ?? 0));
      const refillMs = Math.floor(Number(entry.rateLimitRefillMs ?? 0));
      const valid = Boolean(groupId && groupLabel && category && capacity > 0 && refillMs > 0);
      const definition: AbilityRateLimitDefinition = {
        action,
        targetingMode: String(entry.targetingMode ?? '').toLowerCase(),
        cooldownMs: Math.max(0, Math.floor(Number(entry.cooldownMs ?? 0))),
        groupId,
        groupLabel,
        category,
        capacity,
        refillMs,
        valid,
      };
      this.abilityDefinitions.set(action, definition);
      if (!valid) continue;

      const existing = this.abilityLimitBuckets.get(groupId);
      if (
        existing &&
        (existing.label !== groupLabel ||
          existing.category !== category ||
          existing.capacity !== capacity ||
          existing.refillMs !== refillMs)
      ) {
        inconsistentGroups.add(groupId);
        continue;
      }
      if (!existing) {
        this.abilityLimitBuckets.set(groupId, {
          groupId,
          label: groupLabel,
          category,
          capacity,
          refillMs,
          tokens: capacity,
          lastRefillAt: Date.now(),
        });
      }
    }

    for (const groupId of inconsistentGroups) {
      this.abilityLimitBuckets.delete(groupId);
      for (const definition of this.abilityDefinitions.values()) {
        if (definition.groupId === groupId) definition.valid = false;
      }
      console.warn(`[Limits] Blocked inconsistent ability rate-limit group "${groupId}" in session "${this.sessionId}".`);
    }

    this.abilityLimitsReady = true;
  }

  private refillBucket(bucket: AbilityLimitBucket, now: number): void {
    if (bucket.tokens >= bucket.capacity) {
      bucket.tokens = bucket.capacity;
      bucket.lastRefillAt = now;
      return;
    }
    const elapsed = now - bucket.lastRefillAt;
    const refillCount = Math.floor(elapsed / bucket.refillMs);
    if (refillCount <= 0) return;
    bucket.tokens = Math.min(bucket.capacity, bucket.tokens + refillCount);
    bucket.lastRefillAt += refillCount * bucket.refillMs;
    if (bucket.tokens >= bucket.capacity) bucket.lastRefillAt = now;
  }

  private getBucketRetryAfterMs(bucket: AbilityLimitBucket, now: number): number {
    this.refillBucket(bucket, now);
    return bucket.tokens >= 1 ? 0 : Math.max(1, bucket.refillMs - (now - bucket.lastRefillAt));
  }

  private getSpectatorKey(ws: WebSocket): string | undefined {
    return this.spectators.get(ws)?.spectatorName.trim().toLowerCase();
  }

  private findDamageEntry(key: string): [string, number] | undefined {
    for (const entry of this.spectatorDamage) {
      if (entry[0].toLowerCase() === key) return entry;
    }
    return undefined;
  }

  private moveSpectatorMap<T>(
    map: Map<string, T>,
    oldKey: string,
    nextKey: string,
  ): void {
    const value = map.get(oldKey);
    if (value === undefined || oldKey === nextKey) return;
    map.delete(oldKey);
    map.set(nextKey, value);
  }

  private sendDirect(ws: WebSocket, data: object): void {
    if (ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(data));
  }

  private sendActionResult(ws: WebSocket, result: ActionResultMessage): false {
    const spectatorKey = this.getSpectatorKey(ws);
    if (spectatorKey) {
      let cache = this.cachedActionResults.get(spectatorKey);
      if (!cache) {
        cache = new Map();
        this.cachedActionResults.set(spectatorKey, cache);
      }
      cache.set(result.requestId, { result, expiresAt: Date.now() + 30_000 });
    }
    this.sendDirect(ws, result);
    return false;
  }

  private pruneCachedActionResults(spectatorKey: string): void {
    const cache = this.cachedActionResults.get(spectatorKey);
    if (!cache) return;
    const now = Date.now();
    for (const [requestId, entry] of cache) {
      if (entry.expiresAt <= now) cache.delete(requestId);
    }
    if (cache.size === 0) this.cachedActionResults.delete(spectatorKey);
  }

  private createAbilityLimitState(ws: WebSocket): AbilityLimitStateMessage {
    const now = Date.now();
    const groups: AbilityLimitGroupState[] = [];
    for (const bucket of this.abilityLimitBuckets.values()) {
      this.refillBucket(bucket, now);
      groups.push({
        groupId: bucket.groupId,
        label: bucket.label,
        category: bucket.category,
        capacity: bucket.capacity,
        availableTokens: bucket.tokens,
        refillMs: bucket.refillMs,
        updatedAt: now,
      });
    }

    const personalCooldowns: Record<string, number> = {};
    const spectatorKey = this.getSpectatorKey(ws);
    if (spectatorKey) {
      for (const [action, cooldownEnd] of this.personalCooldowns.get(spectatorKey) ?? []) {
        if (cooldownEnd > now) personalCooldowns[action] = cooldownEnd;
      }
    }
    return { type: 'ability_limit_state', groups, personalCooldowns };
  }

  private sendAbilityLimitState(ws: WebSocket): void {
    this.sendDirect(ws, this.createAbilityLimitState(ws));
  }

  private broadcastAbilityLimitState(): void {
    for (const [ws] of this.spectators) this.sendAbilityLimitState(ws);
  }

  private broadcastSpectatorCount(): void {
    const msg = { type: 'spectator_count', count: this.spectatorCount };
    this.sendToPlayer(msg);
    this.sendToSpectators(msg);
  }

  private broadcastSpectatorList(): void {
    const spectators = Array.from(this.spectators.values(), ({
      spectatorId,
      spectatorName,
    }) => ({ spectatorId, spectatorName }));
    const msg = { type: 'spectator_list', spectators };
    this.sendToPlayer(msg);
    this.sendToSpectators(msg);
  }

  private broadcastDamageSnapshot(): void {
    const damage: Record<string, number> = {};
    for (const [name, total] of this.spectatorDamage) damage[name] = total;
    this.sendToSpectators({ type: 'spectator_damage_snapshot', damage });
  }

  finishGame(playerDeaths: number): GameFinishedMessage {
    if (this.finishedResult) {
      this.sendToPlayer(this.finishedResult);
      return this.finishedResult;
    }

    const ranked = Array.from(this.spectatorParticipants.values(), (participant) => {
      const damageEntry = this.findDamageEntry(
        participant.spectatorName.toLowerCase(),
      );
      return {
        spectatorName: participant.spectatorName,
        damage: Math.max(0, Number(damageEntry?.[1]) || 0),
        joinedOrder: participant.joinedOrder,
      };
    }).sort((a, b) =>
      b.damage - a.damage ||
      a.joinedOrder - b.joinedOrder ||
      a.spectatorName.localeCompare(b.spectatorName)
    );

    const finishedAt = Date.now();
    this.finishedResult = {
      type: 'game_finished',
      sessionId: this.sessionId,
      winnerName: this.playerName,
      level: this.level,
      finishedAt,
      durationMs: Math.max(0, finishedAt - this.createdAt.getTime()),
      playerDeaths: this.hasPlayerDeathSnapshot
        ? this.lastPlayerDeaths
        : Math.max(0, Math.floor(playerDeaths)),
      totalSpectatorDamage: ranked.reduce((sum, entry) => sum + entry.damage, 0),
      leaderboard: ranked.map((entry, index) => ({
        rank: index + 1,
        spectatorName: entry.spectatorName,
        damage: entry.damage,
      })),
    };

    this.pendingGameState = null;
    if (this.gameStateFlushTimer) {
      clearTimeout(this.gameStateFlushTimer);
      this.gameStateFlushTimer = null;
    }

    this.sendToPlayer(this.finishedResult);
    this.sendToSpectators(this.finishedResult);
    return this.finishedResult;
  }

  private broadcastSessionStatus(): void {
    const msg = this.createSessionStatusMessage();
    this.sendToPlayer(msg);
    this.sendToSpectators(msg);
  }

  private createSessionStatusMessage() {
    return {
      type: 'session_status' as const,
      sessionId: this.sessionId,
      bootPhase: this.bootPhase,
      bootMessage: this.bootMessage,
      routeReady: this.routeReady,
    };
  }

  toListEntry(): SessionListEntry {
    return {
      sessionId: this.sessionId,
      playerName: this.playerName,
      level: this.level,
      spectatorCount: this.spectatorCount,
      bootPhase: this.bootPhase,
      bootMessage: this.bootMessage,
      routeReady: this.routeReady,
    };
  }
}
